/**
 * Slide Generator
 * Generates presentation slides from topics
 */

import { ChatOpenAI } from "@langchain/openai";
import { PromptTemplate } from "@langchain/core/prompts";
import { StringOutputParser } from "@langchain/core/output_parsers";
import { retrieveDocuments } from "../utils/vector-store";

const llm = new ChatOpenAI({
  modelName: "gpt-4o",
  temperature: 0.7,
  openAIApiKey: process.env.OPENAI_API_KEY,
});

export interface Slide {
  title: string;
  content: string[];
  notes?: string;
  layout?: "title" | "content" | "two-column" | "image-text" | "conclusion";
  imagePrompt?: string;
}

export interface SlidePresentation {
  title: string;
  subtitle?: string;
  author?: string;
  subject?: string;
  gradeLevel?: number;
  slides: Slide[];
  theme?: string;
  metadata?: any;
}

export interface SlideOptions {
  subject?: string;
  gradeLevel?: number;
  slideCount?: number;
  includeImages?: boolean;
  theme?: "professional" | "educational" | "creative" | "minimal";
  includeNotes?: boolean;
}

/**
 * Generate slide presentation from topic
 */
export async function generateSlides(
  topic: string,
  options: SlideOptions = {}
): Promise<SlidePresentation> {
  const {
    subject,
    gradeLevel,
    slideCount = 10,
    includeImages = true,
    theme = "educational",
    includeNotes = true,
  } = options;

  try {
    // Retrieve relevant documents
    const documents = await retrieveDocuments(topic, {
      subject,
      gradeLevel,
      userRole: "teacher",
      topK: 5,
    });

    // Prepare context
    const context = documents
      .map((doc) => `[${doc.metadata.documentTitle}]\n${doc.content}`)
      .join("\n\n---\n\n");

    // Create prompt
    const slidePrompt = PromptTemplate.fromTemplate(`
You are an expert presentation designer creating educational slides.

TOPIC: {topic}
SUBJECT: {subject}
GRADE LEVEL: {gradeLevel}
NUMBER OF SLIDES: {slideCount}
THEME: {theme}

CONTEXT FROM EDUCATIONAL MATERIALS:
{context}

Create a compelling presentation that educates the audience about the topic.

Slide Structure:
1. Title slide
2-3. Introduction and overview
4-8. Main content (concepts, explanations, examples)
9. Summary/Review
10. Conclusion/Call to action

Requirements:
1. Each slide should have a clear title
2. Content should be concise bullet points (3-5 per slide)
3. Use age-appropriate language for grade {gradeLevel}
4. Include speaker notes for teachers
5. Suggest images where relevant
6. Progressive disclosure of information

Format as JSON:
{{
  "title": "Presentation Title",
  "subtitle": "Subtitle",
  "author": "Generated by AI",
  "slides": [
    {{
      "title": "Slide Title",
      "content": [
        "Bullet point 1",
        "Bullet point 2",
        "Bullet point 3"
      ],
      "notes": "Speaker notes for this slide",
      "layout": "content",
      "imagePrompt": "Description of helpful image"
    }}
  ]
}}

Generate the presentation now:`);

    const chain = slidePrompt.pipe(llm).pipe(new StringOutputParser());

    const response = await chain.invoke({
      topic,
      subject: subject || "General",
      gradeLevel: gradeLevel || "Not specified",
      slideCount,
      theme,
      context: context || "No specific context available - use general knowledge",
    });

    // Parse JSON response
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("Failed to parse slides JSON from response");
    }

    const presentation: SlidePresentation = JSON.parse(jsonMatch[0]);

    // Add metadata
    presentation.subject = subject;
    presentation.gradeLevel = gradeLevel;
    presentation.theme = theme;
    presentation.metadata = {
      topic,
      generatedAt: new Date().toISOString(),
      includeImages,
    };

    return presentation;
  } catch (error: any) {
    console.error("Error generating slides:", error);
    throw new Error(`Slide generation failed: ${error.message}`);
  }
}

/**
 * Generate slides for a specific lesson
 */
export async function generateLessonSlides(
  lessonTitle: string,
  lessonContent: string,
  options: SlideOptions
): Promise<SlidePresentation> {
  const prompt = `${lessonTitle}\n\nContent:\n${lessonContent}`;
  return generateSlides(prompt, options);
}

/**
 * Validate slide presentation
 */
export function validatePresentation(
  presentation: SlidePresentation
): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!presentation.title) errors.push("Presentation must have a title");
  if (!presentation.slides || presentation.slides.length === 0) {
    errors.push("Presentation must have at least one slide");
  }

  presentation.slides.forEach((slide, idx) => {
    if (!slide.title) errors.push(`Slide ${idx + 1}: Missing title`);
    if (!slide.content || slide.content.length === 0) {
      errors.push(`Slide ${idx + 1}: No content`);
    }
  });

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Export slides to different formats
 */
export function exportSlidesToJSON(presentation: SlidePresentation): string {
  return JSON.stringify(presentation, null, 2);
}

export function exportSlidesToMarkdown(presentation: SlidePresentation): string {
  let md = `# ${presentation.title}\n\n`;

  if (presentation.subtitle) {
    md += `## ${presentation.subtitle}\n\n`;
  }

  if (presentation.author) {
    md += `*By ${presentation.author}*\n\n`;
  }

  md += `---\n\n`;

  presentation.slides.forEach((slide, idx) => {
    md += `## Slide ${idx + 1}: ${slide.title}\n\n`;

    slide.content.forEach((point) => {
      md += `- ${point}\n`;
    });

    md += `\n`;

    if (slide.imagePrompt) {
      md += `*[Image: ${slide.imagePrompt}]*\n\n`;
    }

    if (slide.notes) {
      md += `**Speaker Notes:** ${slide.notes}\n\n`;
    }

    md += `---\n\n`;
  });

  return md;
}

export function exportSlidesToHTML(presentation: SlidePresentation): string {
  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${presentation.title}</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background: #f0f0f0;
    }
    .slide {
      width: 960px;
      height: 540px;
      margin: 20px auto;
      background: white;
      padding: 40px;
      box-shadow: 0 4px 6px rgba(0,0,0,0.1);
      page-break-after: always;
    }
    .slide h1 {
      color: #333;
      margin-bottom: 20px;
      font-size: 2.5em;
    }
    .slide h2 {
      color: #666;
      margin-bottom: 30px;
      font-size: 1.8em;
    }
    .slide ul {
      font-size: 1.3em;
      line-height: 1.8;
    }
    .notes {
      background: #fffacd;
      padding: 15px;
      margin-top: 20px;
      border-left: 4px solid #ffd700;
      font-size: 0.9em;
    }
  </style>
</head>
<body>
`;

  // Title slide
  html += `
  <div class="slide">
    <h1>${presentation.title}</h1>
    ${presentation.subtitle ? `<h2>${presentation.subtitle}</h2>` : ""}
    ${presentation.author ? `<p><em>${presentation.author}</em></p>` : ""}
  </div>
`;

  // Content slides
  presentation.slides.forEach((slide) => {
    html += `
  <div class="slide">
    <h2>${slide.title}</h2>
    <ul>
      ${slide.content.map((point) => `<li>${point}</li>`).join("\n      ")}
    </ul>
    ${slide.notes ? `<div class="notes"><strong>Notes:</strong> ${slide.notes}</div>` : ""}
  </div>
`;
  });

  html += `
</body>
</html>`;

  return html;
}

/**
 * Add transitions and animations metadata
 */
export function addAnimations(
  presentation: SlidePresentation,
  animationType: "fade" | "slide" | "zoom" | "none" = "fade"
): SlidePresentation {
  return {
    ...presentation,
    metadata: {
      ...presentation.metadata,
      animations: {
        type: animationType,
        duration: 0.5,
        enabled: animationType !== "none",
      },
    },
  };
}

/**
 * Generate slides summary for quick preview
 */
export function generateSummary(presentation: SlidePresentation): string {
  const slideCount = presentation.slides.length;
  const totalBullets = presentation.slides.reduce(
    (sum, slide) => sum + slide.content.length,
    0
  );

  return `
Presentation: ${presentation.title}
Slides: ${slideCount}
Total bullet points: ${totalBullets}
Subject: ${presentation.subject || "N/A"}
Grade Level: ${presentation.gradeLevel || "N/A"}
Theme: ${presentation.theme || "default"}
  `.trim();
}

/**
 * Create handout version (condensed)
 */
export function createHandout(presentation: SlidePresentation): string {
  let handout = `# ${presentation.title}\n`;
  if (presentation.subtitle) handout += `${presentation.subtitle}\n`;
  handout += `\n---\n\n`;

  presentation.slides.forEach((slide, idx) => {
    if (idx === 0) return; // Skip title slide

    handout += `### ${slide.title}\n\n`;
    slide.content.forEach((point) => {
      handout += `- ${point}\n`;
    });
    handout += `\n`;
  });

  return handout;
}
